export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';

export const BASE_CONNECT_START = 'BASE_CONNECT_START';
export const BASE_CONNECTED = 'BASE_CONNECTED';
export const BASE_CONNECT_FAIL = 'BASE_CONNECT_FAIL';
export const BASE_DISCONNECT = 'BASE_DISCONNECT';

export const MY_INFO_START = 'INFO_START';
export const MY_INFO_SUCCESS = 'INFO_SUCCESS';
export const MY_INFO_UPDATE = 'INFO_UPDATE';
export const MY_INFO_FAIL = 'INFO_FAIL';

export const CHAT_START = 'CHAT_START';
export const CHAT_FAIL = 'CHAT_FAIL';
export const CHAT_STOP = 'CHAT_STOP';
export const CHAT_HIDE = 'CHAT_HIDE';
export const CHAT_CREATE = 'CHAT_CREATE';
export const CHAT_CREATED = 'CHAT_CREATED';
export const CHAT_BLOCK_RECIPIENT = 'CHAT_BLOCK_RECIPIENT';
export const CHAT_UNBLOCK_RECIPIENT = 'CHAT_UNBLOCK_RECIPIENT';
export const CHAT_CLEAR_HISTORY = 'CHAT_CLEAR_HISTORY';
export const CHAT_HANDLE_REQUEST = 'CHAT_HANDLE_REQUEST';
export const CHAT_ACCEPT_REQUEST = 'CHAT_ACCEPT_REQUEST';
export const CHAT_DELETE_REQUEST = 'CHAT_DELETE_REQUEST';
export const CHAT_MESSAGES_ADD = 'CHAT_MESSAGES_ADD';
export const CHAT_MESSAGES_START = 'CHAT_MESSAGES_START';
export const CHAT_MESSAGES_SUCCESS = 'CHAT_MESSAGES_SUCCESS';
export const CHAT_MESSAGE_SEND = 'CHAT_MESSAGE_SEND';
export const CHAT_RECIPIENT_START = 'CHAT_RECIPIENT_START';
export const CHAT_RECIPIENT_SUCCESS = 'CHAT_RECIPIENT_SUCCESS';
export const CHAT_RECIPIENT_DELETE = 'CHAT_RECIPIENT_DELETE';
export const CHAT_ACTION_START = 'CHAT_ACTION_START';
export const CHAT_ACTION_SUCCESS = 'CHAT_ACTION_SUCCESS';

export const CONTACTS_START = 'CONTACTS_START';
export const CONTACTS_ADD = 'CONTACTS_ADD';
export const CONTACTS_REMOVE = 'CONTACTS_REMOVE';
export const CONTACTS_SUCCESS = 'CONTACTS_SUCCESS';
export const CONTACTS_REQUEST_START = 'CONTACTS_REQUEST_START';
export const CONTACTS_REQUEST_SUCCESS = 'CONTACTS_REQUEST_SUCCESS';
export const CONTACTS_REQUEST_FAIL = 'CONTACTS_REQUEST_FAIL';
export const CONTACTS_INFO_CONTACT = 'CONTACTS_INFO_CONTACT';

export const DISCUSSIONS_START = 'DISCUSSIONS_START';
export const DISCUSSIONS_ADD = 'DISCUSSIONS_ADD';
export const DISCUSSIONS_REMOVE = 'DISCUSSIONS_REMOVE';
export const DISCUSSIONS_SUCCESS = 'DISCUSSIONS_SUCCESS';
export const DISCUSSIONS_UPDATE = 'DISCUSSIONS_UPDATE';

export const EMOJIS_START = 'EMOJIS_START';
export const EMOJIS_SUCCESS = 'EMOJIS_SUCCESS';
export const EMOJIS_FAIL = 'EMOJIS_FAIL';

export const NOTIFICATIONS_START = 'NOTIFICATIONS_START';
export const NOTIFICATIONS_SUCCESS = 'NOTIFICATIONS_SUCCESS';
export const NOTIFICATIONS_ADD = 'NOTIFICATIONS_ADD';
export const NOTIFICATIONS_SEEN = 'NOTIFICATIONS_SEEN';